### PR TITLE
added endpoint owner

### PR DESCRIPTION
**Pull request by tanneberger**
## Description
Added microservice endpoint "owner" which returns the owner user uuid if the given device exists.

## Related Issue

See #14 

## How Has This Been Tested?

Tested with official [game-server](https://github.com/cryptic-game/server).

## Motivation and Context

Needed for service.

## How Has This Been Tested?

Test needed.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by felixevers — DISMISSED** [review]
PEP8 accepts the empty lines. But just leave them out next time.

**Comment by felixevers** [comment]
@mieasy The experimental branch is currently blocked by changes from @sunti27. So this change must merge directly into master.

**Comment by ghost** [comment]
1. @use-to What do you mean by "currently blocked by changes from..."? If my interpretation is correct (that sunti27 should have access to the experimental branch), it is correct as it is.
2. Furthermore we are not allowed to directly merge (except from experimental of course) or commit into the master. [More on that here](https://github.com/cryptic-game/cryptic/blob/master/conventions.md#master-branch).
3. @SpartanerSpaten The code by the conventions standpoint ok, but, like @use-to already said, those empty lines don't look or are reasonable. I'll add something about that to the conventions soo. Till then I commited a small fix.

All in all I can't approve this, mostly because of the second point.

**Comment by ghost** [comment]
I forgot to mention something:

> How Has This Been Tested? - Test needed.

Is not ok. I don't think I have to explain why.

**Pull request merged**
